version: '3.9'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_gnut
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gnut06
    ports:
      - "3306:3306"
    
    volumes:
      - ./mysql:/var/lib/mysql
 
  
  phpmyadmin:
    image: phpmyadmin:fpm-alpine
    container_name: phpmyadmin_gnut
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "9000:9000"
    volumes:
        - phpmyadmin:/var/www/html
    depends_on:
      - mysql


  maildev:
    image: maildev/maildev
    container_name: maildev_gnut
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - 1080:80
      - 1025:25
    restart: always

  symfony:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - USER_UID=82
        - USER_GID=82
    container_name: symfony_asso
    restart: always
    environment:
      DATABASE_URL: "mysql://root:root@mysql:3306/gnut06?serverVersion=5.7&charset=utf8mb4"
    volumes:
      - ./app:/var/www/app
    ports:
      - "9003:9003"
    expose:
      - 9000
    depends_on:
      - mysql

  apache:
    build:
      context: ./app
      dockerfile: apache.Dockerfile
    container_name: apache_gnut
    restart: always
    ports:
      - "8080:8080"
      - "8000:80"
      - "443:443"
    volumes:
      - ./app:/var/www/app
      - phpmyadmin:/var/www/html


volumes:
  mysql:
  phpmyadmin: