services:
    App\Service\RecaptchaVerifier:
        class: App\Tests\Stub\RecaptchaVerifierStub

    App\Service\HelloAssoApiService:
        class: App\Tests\Stub\HelloAssoApiServiceStub

    App\Service\HelloAssoAuthService:
        class: App\Service\HelloAssoAuthService
        arguments:
            $requestStack: '@request_stack'
            $client: '@helloasso.client'
            $apiClientId: 'test_client_id'
            $apiClientSecret: 'test_client_secret'
